# Generated by Django 2.1.2 on 2018-11-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20181124_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='user',
        ),
        migrations.AddField(
            model_name='hobby',
            name='users',
            field=models.ManyToManyField(to='mainApp.UserProfile'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='hobbyName',
            field=models.CharField(max_length=100),
        ),
    ]
