# Generated by Django 2.1.2 on 2018-12-08 16:34

from django.db import migrations, models
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='likes',
            field=django_mysql.models.ListTextField(models.CharField(max_length=150), default=django.utils.timezone.now, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reject',
            field=django_mysql.models.ListTextField(models.CharField(max_length=150), default=django.utils.timezone.now, size=None),
            preserve_default=False,
        ),
    ]
