# Generated by Django 2.1.2 on 2018-12-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20181208_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='reject',
            new_name='rejects',
        ),
    ]
