# Generated by Django 2.1.2 on 2018-12-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20181208_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
    ]
